CC=gcc
CFLAGS=-c -Wall -Werror -fpic
INCLUDES=-Isrc -I/usr/include/linux -I/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include
SRCS=src/vector2d.c
OBJS = $(SRCS:.c=.o)

# define the executable file 
#MAIN = mycc

#gcc -c -Wall -Werror -fpic -Isrc src/vector2d.c -obin/lib//vector2d.o
#gcc -shared -obin/lib/libvector2d.so bin/lib/vector2d.o
#rm bin/lib/vector2d.o
#gcc -Lbin/lib -Wall tests/collision.c -obin/tests/collision.exe libvector2d
#
# The following part of the makefile is generic; it can be used to 
# build any executable just by changing the definitions above and by
# deleting dependencies appended to the file from 'make depend'
#

.PHONY: depend clean

all:	$(MAIN)
		@echo  "Simple compiler named mycc has been compiled"

$(MAIN): $(OBJS) 
		$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

# this is a suffix replacement rule for building .o's from .c's
# it uses automatic variables $<: the name of the prerequisite of
# the rule(a .c file) and $@: the name of the target of the rule (a .o file) 
# (see the gnu make manual section about automatic variables)
.c.o:
		$(CC) $(CFLAGS) $(INCLUDES) -c $<  -o $@

clean:
		$(RM) *.o *~ $(MAIN)

depend: $(SRCS)
		makedepend $(INCLUDES) $^

# DO NOT DELETE THIS LINE -- make depend needs it

src/vector2d.o: /usr/include/stdio.h /usr/include/features.h
src/vector2d.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
src/vector2d.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/vector2d.o: /usr/include/linux/stddef.h /usr/include/bits/types.h
src/vector2d.o: /usr/include/bits/typesizes.h /usr/include/libio.h
src/vector2d.o: /usr/include/_G_config.h /usr/include/wchar.h
src/vector2d.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdarg.h
src/vector2d.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
src/vector2d.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdbool.h
src/vector2d.o: /usr/include/math.h /usr/include/bits/huge_val.h
src/vector2d.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
src/vector2d.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
src/vector2d.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
src/vector2d.o: /usr/include/assert.h
